#!/bin/bash

ART_PATH=/usr/local/share/git-fun-commit/arts

if [ -z "$2" ]
then
    art_name=`ls -1 $ART_PATH | shuf -n1`
else
    art_name="$2.art"
fi

art=`cat $ART_PATH/$art_name`
git commit -F- <<EOF
$1
$art
EOF
